from Phidget22.Devices.DCMotor import *
from Phidget22.Devices.RCServo import *
from time import *
dcMotor0 = RCServo()
dcMotor0.setDeviceSerialNumber(19875)
dcMotor0.openWaitForAttachment(5000)
dcMotor0.setTargetPosition(30)
dcMotor0.setEngaged(True)
dcMotor0.setTargetPosition(100)
sleep(1)
dcMotor0.setTargetPosition(30)
sleep(1)
dcMotor0.setTargetPosition(100)
sleep(1)
dcMotor0.setTargetPosition(30)
sleep(1)
dcMotor0.setTargetPosition(100)
sleep(1)
dcMotor0.setTargetPosition(30)
sleep(1)
dcMotor0.setTargetPosition(100)
sleep(1)
dcMotor0.setTargetPosition(30)
sleep(5)
dcMotor0.close()